stoneItem = { type = 'material', sprite = stoneItemSprite}
ironItem = { type = 'material', sprite = ironItemSprite}
goldItem = { type = 'material', sprite = goldItemSprite}
diamondItem = { type = 'material', sprite = diamondItemSprite}
amethystItem = { type = 'material', sprite = amethystItemSprite}
forrestiteItem = { type = 'material', sprite = forrestiteItemSprite}
carrotItem = { type = 'material', sprite = carrotItemSprite}
breadItem = { type = 'material', sprite = breadItemSprite}
rubyItem = { type = 'material', sprite = rubyItemSprite}