require("sprites")

rockParticleSystem = love.graphics.newParticleSystem(spriteSheet, 100)
rockParticleSystem:setQuads(rockParticle)

rockParticleSystem:setParticleLifetime(1, 3)
rockParticleSystem:setSizeVariation(0.5)
rockParticleSystem:setSpeed(30,50)
rockParticleSystem:setDirection(math.pi / 2)
rockParticleSystem:setLinearAcceleration(0,70,0,90)
rockParticleSystem:setSpread(1)
rockParticleSystem:setSpin(5,7)
rockParticleSystem:setRotation(math.random(0,360))

ironParticleSystem = love.graphics.newParticleSystem(spriteSheet, 100)
ironParticleSystem:setQuads(ironParticle)

ironParticleSystem:setParticleLifetime(1, 3)
ironParticleSystem:setSizeVariation(0.5)
ironParticleSystem:setSpeed(30,50)
ironParticleSystem:setDirection(math.pi / 2)
ironParticleSystem:setLinearAcceleration(0,70,0,90)
ironParticleSystem:setSpread(1)
ironParticleSystem:setSpin(5,7)
ironParticleSystem:setRotation(math.random(0,360))

goldParticleSystem = love.graphics.newParticleSystem(spriteSheet, 100)
goldParticleSystem:setQuads(goldParticle)

goldParticleSystem:setParticleLifetime(1, 3)
goldParticleSystem:setSizeVariation(0.5)
goldParticleSystem:setSpeed(30,50)
goldParticleSystem:setDirection(math.pi / 2)
goldParticleSystem:setLinearAcceleration(0,70,0,90)
goldParticleSystem:setSpread(1)
goldParticleSystem:setSpin(5,7)
goldParticleSystem:setRotation(math.random(0,360))

diamondParticleSystem = love.graphics.newParticleSystem(spriteSheet, 100)
diamondParticleSystem:setQuads(diamondParticle)

diamondParticleSystem:setParticleLifetime(1, 3)
diamondParticleSystem:setSizeVariation(0.5)
diamondParticleSystem:setSpeed(30,50)
diamondParticleSystem:setDirection(math.pi / 2)
diamondParticleSystem:setLinearAcceleration(0,70,0,90)
diamondParticleSystem:setSpread(1)
diamondParticleSystem:setSpin(5,7)
diamondParticleSystem:setRotation(math.random(0,360))

amethystParticleSystem = love.graphics.newParticleSystem(spriteSheet, 100)
amethystParticleSystem:setQuads(amethestParticle)

amethystParticleSystem:setParticleLifetime(1, 3)
amethystParticleSystem:setSizeVariation(0.5)
amethystParticleSystem:setSpeed(30,50)
amethystParticleSystem:setDirection(math.pi / 2)
amethystParticleSystem:setLinearAcceleration(0,70,0,90)
amethystParticleSystem:setSpread(1)
amethystParticleSystem:setSpin(5,7)
amethystParticleSystem:setRotation(math.random(0,360))

forrestiteParticleSystem = love.graphics.newParticleSystem(spriteSheet, 100)
forrestiteParticleSystem:setQuads(forrestiteParticle)

forrestiteParticleSystem:setParticleLifetime(1, 3)
forrestiteParticleSystem:setSizeVariation(0.5)
forrestiteParticleSystem:setSpeed(30,50)
forrestiteParticleSystem:setDirection(math.pi / 2)
forrestiteParticleSystem:setLinearAcceleration(0,70,0,90)
forrestiteParticleSystem:setSpread(1)
forrestiteParticleSystem:setSpin(5,7)
forrestiteParticleSystem:setRotation(math.random(0,360))